In [1]:
import pandas as pd
import numpy as np
import operator
import seaborn as sns
import matplotlib.pyplot as plt
from scipy.stats import norm



pd.options.display.float_format = '{:20,.2f}'.format
%matplotlib inline
plt.style.use('ggplot')

In [2]:
# function to clean rookie df
def rookie_df_clean(data, year):
    data = data[['Rnd', 'Player', 'Age']] #removes columns not wanted
    
    x = year
    new_data = {'Rookie Year': x}
    data = data.assign(**new_data) # adding new column data rookie year
    return data

In [3]:
# function to clean yearly data
def season_df_clean(data, year):
    data = data[['player', 
       'avg_depth_of_target', 'avoided_tackles', 'caught_percent',
       
        
       'grades_offense',
        'longest',
       'receptions', 'routes',
       'targeted_qb_rating', 'targets',  'yards', 'yards_after_catch',
       'yards_after_catch_per_reception', 'yards_per_reception', 'yprr']] #removes columns not wanted
    data = data.rename(columns={'player': 'Player'})
    new_data = {'ypt' : data['yards'] / data['targets'] }
    data = data.assign(**new_data) # adds new coplumn
   
    
    return data

In [4]:
# function to merge rookie season year and add stats for that year.

def merge_rookieyear_stats(df_rookie, df_stats):
    df1 = pd.merge(df_rookie, df_stats, on= 'Player', how= 'left')
    return df1

In [5]:
# importing rookie for 2023
df_wr23r = pd.read_csv('2023rookie.csv')

df_wr23r.head()

,Rnd,Pick,Tm,Player,Pos,Age,To,AP1,PB,St,...,TD.1,Rec,Yds.2,TD.2,Solo,Int.1,Sk,College/Univ,Unnamed: 28,-9999
0,1,20,SEA,Jaxon Smith-Njigba,WR,21,"2,023.00",0,0,0,...,0.00,63.00,628.00,4.00,NaN,NaN,NaN,Ohio St.,College Stats,SmitJa06
1,1,21,LAC,Quentin Johnston,WR,22,"2,023.00",0,0,0,...,0.00,38.00,431.00,2.00,NaN,NaN,NaN,TCU,College Stats,JohnQu02
2,1,22,BAL,Zay Flowers,WR,22,"2,023.00",0,0,0,...,1.00,77.00,858.00,5.00,NaN,NaN,NaN,Boston Col.,College Stats,FlowZa00
3,1,23,MIN,Jordan Addison,WR,21,"2,023.00",0,0,0,...,0.00,70.00,911.00,10.00,NaN,NaN,NaN,USC,College Stats,AddiJo00
4,2,39,CAR,Jonathan Mingo,WR,22,"2,023.00",0,0,0,...,0.00,43.00,418.00,0.00,NaN,NaN,NaN,Mississippi,College Stats,MingJo00

In [6]:
# clean df add year
df_wr23r = rookie_df_clean(df_wr23r, 2023)
df_wr23r.head()

   Rnd              Player  Age  Rookie Year
0    1  Jaxon Smith-Njigba   21         2023
1    1    Quentin Johnston   22         2023
2    1         Zay Flowers   22         2023
3    1      Jordan Addison   21         2023
4    2      Jonathan Mingo   22         2023

In [7]:
df_wr23r.shape

(33, 4)

In [8]:
df23 = pd.read_csv('rec2023.csv')

df23.head()

,player,player_id,position,team_name,player_game_count,avg_depth_of_target,avoided_tackles,caught_percent,contested_catch_rate,contested_receptions,...,targeted_qb_rating,targets,touchdowns,wide_rate,wide_snaps,yards,yards_after_catch,yards_after_catch_per_reception,yards_per_reception,yprr
0,CeeDee Lamb,61570,WR,DAL,17,10.10,20,75.40,42.30,11,...,125.70,179,12,41.80,282,1749,674,5.00,13.00,2.78
1,Davante Adams,8688,WR,LV,17,11.10,8,60.20,35.30,12,...,81.10,171,8,82.00,496,1144,337,3.30,11.10,1.97
2,Tyreek Hill,10799,WR,MIA,16,11.30,26,71.30,35.00,7,...,119.80,167,13,60.70,298,1799,657,5.50,15.10,3.82
3,Garrett Wilson,97405,WR,NYJ,17,10.60,19,58.30,29.70,11,...,68.10,163,3,68.80,490,1042,319,3.40,11.00,1.55
4,Stefon Diggs,9579,WR,BUF,17,10.80,21,67.30,41.40,12,...,95.50,159,8,63.70,402,1183,404,3.80,11.10,1.99

In [9]:
# call function to clean data
df23 = season_df_clean(df23, 2023)
df23.head()

,Player,avg_depth_of_target,avoided_tackles,caught_percent,grades_offense,longest,receptions,routes,targeted_qb_rating,targets,yards,yards_after_catch,yards_after_catch_per_reception,yards_per_reception,yprr,ypt
0,CeeDee Lamb,10.10,20,75.40,91.10,92,135,629,125.70,179,1749,674,5.00,13.00,2.78,9.77
1,Davante Adams,11.10,8,60.20,79.10,46,103,582,81.10,171,1144,337,3.30,11.10,1.97,6.69
2,Tyreek Hill,11.30,26,71.30,93.70,78,119,471,119.80,167,1799,657,5.50,15.10,3.82,10.77
3,Garrett Wilson,10.60,19,58.30,72.90,68,95,674,68.10,163,1042,319,3.40,11.00,1.55,6.39
4,Stefon Diggs,10.80,21,67.30,81.10,55,107,593,95.50,159,1183,404,3.80,11.10,1.99,7.44

In [10]:
df23.shape

(482, 16)

In [11]:
df_wr23r = merge_rookieyear_stats(df_wr23r, df23)
df_wr23r.head()

,Rnd,Player,Age,Rookie Year,avg_depth_of_target,avoided_tackles,caught_percent,grades_offense,longest,receptions,routes,targeted_qb_rating,targets,yards,yards_after_catch,yards_after_catch_per_reception,yards_per_reception,yprr,ypt
0,1,Jaxon Smith-Njigba,21,2023,6.40,6.00,70.00,63.30,35.00,63.00,477.00,95.00,90.00,628.00,370.00,5.90,10.00,1.32,6.98
1,1,Quentin Johnston,22,2023,13.00,5.00,58.50,58.90,57.00,38.00,488.00,82.30,65.00,431.00,152.00,4.00,11.30,0.88,6.63
2,1,Zay Flowers,22,2023,8.80,19.00,74.00,75.60,75.00,77.00,522.00,110.20,104.00,858.00,396.00,5.10,11.10,1.64,8.25
3,1,Jordan Addison,21,2023,12.50,5.00,67.30,68.60,62.00,70.00,606.00,98.70,104.00,911.00,267.00,3.80,13.00,1.50,8.76
4,2,Jonathan Mingo,22,2023,10.60,5.00,51.80,54.70,40.00,43.00,539.00,56.20,83.00,418.00,161.00,3.70,9.70,0.78,5.04

In [12]:
df_wr23r.shape

(33, 19)

In [13]:
df_wr22r = pd.read_csv('2022Rookie.csv')

# clean df add year
df_wr22r = rookie_df_clean(df_wr22r, 2022)
df22 = pd.read_csv('rec2022.csv')

df22 = season_df_clean(df22, 2022)
df_wr22r = merge_rookieyear_stats(df_wr22r, df22)
df_wr22r.shape

(28, 19)

In [14]:
df_wr21r = pd.read_csv('2021rookie.csv')
# clean df add year
df_wr21r = rookie_df_clean(df_wr21r, 2021)

df21 = pd.read_csv('rec2021.csv')
df21 = season_df_clean(df21, 2021)

df_wr21r = merge_rookieyear_stats(df_wr21r, df21)
df_wr21r.shape

(35, 19)

In [15]:
df_wr20r = pd.read_csv('2020rookies.csv')
# clean df add year
df_wr20r = rookie_df_clean(df_wr20r, 2020)

df20 = pd.read_csv('rec2020.csv')
df20 = season_df_clean(df20, 2020)

df_wr20r = merge_rookieyear_stats(df_wr20r, df20)
df_wr20r.shape

(35, 19)

In [16]:
df_wr19r = pd.read_csv('2019rookies.csv')
# clean df add year
df_wr19r = rookie_df_clean(df_wr19r, 2019)

df19 = pd.read_csv('rec2019.csv')
df19 = season_df_clean(df19, 2019)

df_wr19r = merge_rookieyear_stats(df_wr19r, df19)
df_wr19r.shape

(28, 19)

In [17]:
df_wr18r = pd.read_csv('2018rookies.csv')
# clean df add year
df_wr18r = rookie_df_clean(df_wr18r, 2018)

df18 = pd.read_csv('rec2018.csv')
df18 = season_df_clean(df18, 2018)

df_wr18r = merge_rookieyear_stats(df_wr18r, df18)
df_wr18r.shape

(34, 19)

In [18]:
df_wr17r = pd.read_csv('2017rookies.csv')
# clean df add year
df_wr17r = rookie_df_clean(df_wr17r, 2017)


df17 = pd.read_csv('rec2017.csv')
df17 = season_df_clean(df17, 2017)

df_wr17r = merge_rookieyear_stats(df_wr17r, df17)
df_wr17r.shape

(32, 19)

In [19]:
df_wr16r = pd.read_csv('2016rookies.csv')
# clean df add year
df_wr16r = rookie_df_clean(df_wr16r, 2016)

df16 = pd.read_csv('rec2016.csv')
df16 = season_df_clean(df16, 2016)

df_wr16r = merge_rookieyear_stats(df_wr16r, df16)
df_wr16r.shape

(31, 19)

In [20]:
df_wr15r = pd.read_csv('2015rookies.csv')
# clean df add year
df_wr15r = rookie_df_clean(df_wr15r, 2015)

df15 = pd.read_csv('rec2015.csv')
df15 = season_df_clean(df15, 2015)

df_wr15r = merge_rookieyear_stats(df_wr15r, df15)
df_wr15r.shape

(34, 19)

In [21]:
df_wr14r = pd.read_csv('2014rookies.csv')
# clean df add year
df_wr14r = rookie_df_clean(df_wr14r, 2014)

df14 = pd.read_csv('rec2014.csv')
df14 = season_df_clean(df14, 2014)

df_wr14r = merge_rookieyear_stats(df_wr14r, df14)
df_wr14r.shape

(34, 19)

In [22]:
df_wr13r = pd.read_csv('2013rookies.csv')
# clean df add year
df_wr13r = rookie_df_clean(df_wr13r, 2013)

df13 = pd.read_csv('rec2013.csv')
df13 = season_df_clean(df13, 2013)

df_wr13r = merge_rookieyear_stats(df_wr13r, df13)
df_wr13r.shape

(28, 19)

In [23]:
df_wr12r = pd.read_csv('2012rookies.csv',  encoding='utf-8', encoding_errors='replace')
# clean df add year
df_wr12r = rookie_df_clean(df_wr12r, 2012)

df12 = pd.read_csv('rec2012.csv',  encoding='utf-8', encoding_errors='replace')
df12 = season_df_clean(df12, 2012)

df_wr12r = merge_rookieyear_stats(df_wr12r, df12)
df_wr12r.shape

(253, 19)

In [24]:
df_wr11r = pd.read_csv('2011rookies.csv')
# clean df add year
df_wr11r = rookie_df_clean(df_wr11r, 2011)

df11 = pd.read_csv('rec2011.csv')
df11 = season_df_clean(df11, 2011)

df_wr11r = merge_rookieyear_stats(df_wr11r, df11)
df_wr11r.shape

(254, 19)

In [25]:
df_wr10r = pd.read_csv('2010rookies.csv')
# clean df add year
df_wr10r = rookie_df_clean(df_wr10r, 2010)

df10 = pd.read_csv('rec2010.csv')
df10 = season_df_clean(df10, 2010)

df_wr10r = merge_rookieyear_stats(df_wr10r, df10)
df_wr10r.shape

(32, 19)

In [26]:
df_wr9r = pd.read_csv('2009rookies.csv')
# clean df add year
df_wr9r = rookie_df_clean(df_wr9r, 2009)

df9 = pd.read_csv('rec2009.csv')
df9 = season_df_clean(df9, 2009)

df_wr9r = merge_rookieyear_stats(df_wr9r, df9)
df_wr9r.shape

(34, 19)

In [27]:
df_wr8r = pd.read_csv('2008rookies.csv')
# clean df add year
df_wr8r = rookie_df_clean(df_wr8r, 2008)

df8 = pd.read_csv('rec2008.csv')
df8 = season_df_clean(df8, 2008)

df_wr8r = merge_rookieyear_stats(df_wr8r, df8)
df_wr8r.shape

(252, 19)

In [28]:
df_wr7r = pd.read_csv('2007rookies.csv', encoding='utf-8', encoding_errors='replace')
# clean df add year
df_wr7r = rookie_df_clean(df_wr7r, 2007)

df7 = pd.read_csv('rec2007.csv')
df7 = season_df_clean(df7, 2007)

df_wr7r = merge_rookieyear_stats(df_wr7r, df7)
df_wr7r.shape

(36, 19)

In [29]:
df_wr6r = pd.read_csv('2006rookies.csv')
# clean df add year
df_wr6r = rookie_df_clean(df_wr6r, 2006)

df6 = pd.read_csv('rec2006.csv')
df6 = season_df_clean(df6, 2006)

df_wr6r = merge_rookieyear_stats(df_wr6r, df6)
df_wr6r.shape

(30, 19)

In [30]:
# combining all the rookie df into 1 using concat     
frames = [ df_wr22r, df_wr21r, df_wr20r, df_wr19r, df_wr18r, df_wr17r, df_wr16r, df_wr15r, df_wr14r,
          df_wr13r, df_wr12r, df_wr11r, df_wr10r, df_wr9r, df_wr8r, df_wr7r, df_wr6r]
df_rookies = pd.concat(frames)
df_rookies.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1210 entries, 0 to 29
Data columns (total 19 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Rnd                              547 non-null    float64
 1   Player                           547 non-null    object
 2   Age                              536 non-null    float64
 3   Rookie Year                      1210 non-null   int64
 4   avg_depth_of_target              362 non-null    float64
 5   avoided_tackles                  362 non-null    float64
 6   caught_percent                   362 non-null    float64
 7   grades_offense                   362 non-null    float64
 8   longest                          362 non-null    float64
 9   receptions                       362 non-null    float64
 10  routes                           362 non-null    float64
 11  targeted_qb_rating               362 non-null    float64
 12  targets                          362 non-null    float64
 13  yards                            362 non-null    float64
 14  yards_after_catch                362 non-null    float64
 15  yards_after_catch_per_reception  342 non-null    float64
 16  yards_per_reception              342 non-null    float64
 17  yprr                             362 non-null    float64
 18  ypt                              362 non-null    float64
dtypes: float64(17), int64(1), object(1)
memory usage: 189.1+ KB

In [31]:
df_rookies.shape
#makning sure data looks good

(1210, 19)

In [32]:
df_rookies.tail(5)
# quick peak at the data

,Rnd,Player,Age,Rookie Year,avg_depth_of_target,avoided_tackles,caught_percent,grades_offense,longest,receptions,routes,targeted_qb_rating,targets,yards,yards_after_catch,yards_after_catch_per_reception,yards_per_reception,yprr,ypt
25,7.00,Devin Aromashodu,22.00,2006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,7.00,Ben Obomanu,22.00,2006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,7.00,David Anderson,23.00,2006,6.00,3.00,100.00,78.40,27.00,1.00,6.00,118.80,1.00,27.00,21.00,21.00,27.00,4.50,27.00
28,7.00,Marques Colston,23.00,2006,10.90,5.00,64.20,81.50,86.00,70.00,447.00,108.30,109.00,"1,038.00",354.00,5.10,14.80,2.32,9.52
29,7.00,Kevin McMahan,NaN,2006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [33]:
print(df_wr23r)

    Rnd              Player  Age  Rookie Year  avg_depth_of_target  \
0     1  Jaxon Smith-Njigba   21         2023                 6.40
1     1    Quentin Johnston   22         2023                13.00
2     1         Zay Flowers   22         2023                 8.80
3     1      Jordan Addison   21         2023                12.50
4     2      Jonathan Mingo   22         2023                10.60
5     2         Jayden Reed   23         2023                10.30
6     2         Rashee Rice   23         2023                 5.20
7     2         Marvin Mims   21         2023                  NaN
8     3           Tank Dell   23         2023                14.40
9     3         Jalin Hyatt   21         2023                20.70
10    3      Cedric Tillman   23         2023                12.20
11    3          Josh Downs   22         2023                 7.40
12    3      Michael Wilson   23         2023                14.10
13    3          Tre Tucker   22         2023                19.20
14    4        Derius Davis   22         2023                -2.10
15    4       Charlie Jones   24         2023                 8.80
16    4         Tyler Scott   21         2023                12.50
17    5      Justin Shorter   23         2023                  NaN
18    5    Dontayvion Wicks   22         2023                10.60
19    5          Puka Nacua   22         2023                 9.40
20    6   Parker Washington   21         2023                 7.90
21    6      Kayshon Boutte   21         2023                19.10
22    6         Trey Palmer   22         2023                11.20
23    6          A.T. Perry   23         2023                17.30
24    6      Elijah Higgins   22         2023                 7.40
25    6   Xavier Hutchinson   23         2023                12.20
26    6      Andrei Iosivas   23         2023                 9.40
27    6     Demario Douglas   22         2023                 8.00
28    7       Antoine Green   23         2023                 6.00
29    7       Colton Dowell   24         2023                20.50
30    7        Jalen Brooks   23         2023                 5.70
31    7         Ronnie Bell   23         2023                12.60
32    7        Grant Dubose   22         2023                  NaN

        avoided_tackles       caught_percent       grades_offense  \
0                  6.00                70.00                63.30
1                  5.00                58.50                58.90
2                 19.00                74.00                75.60
3                  5.00                67.30                68.60
4                  5.00                51.80                54.70
5                  6.00                71.10                75.10
6                 12.00                79.00                85.00
7                   NaN                  NaN                  NaN
8                  3.00                63.50                83.40
9                  1.00                57.50                59.70
10                 4.00                50.00                55.50
11                 9.00                72.30                70.30
12                 6.00                64.40                68.30
13                 1.00                55.90                65.20
14                 3.00                88.20                60.50
15                 0.00                77.80                65.80
16                 1.00                54.80                52.70
17                  NaN                  NaN                  NaN
18                 9.00                68.40                78.40
19                11.00                68.60                87.90
20                 2.00                84.20                51.10
21                 0.00                28.60                47.10
22                 1.00                59.10                51.30
23                 0.00                66.70                61.00
24                 0.00                82.40                63.60
25                 0.00                44.40                46.90
26                 0.00                60.00                61.20
27                12.00                64.50                74.40
28                 0.00                50.00                53.70
29                 0.00                50.00                54.40
30                 0.00               100.00                65.10
31                 0.00                46.20                61.10
32                  NaN                  NaN                  NaN

                longest           receptions               routes  \
0                 35.00                63.00               477.00
1                 57.00                38.00               488.00
2                 75.00                77.00               522.00
3                 62.00                70.00               606.00
4                 40.00                43.00               539.00
5                 59.00                64.00               387.00
6                 67.00                79.00               392.00
7                   NaN                  NaN                  NaN
8                 68.00                47.00               320.00
9                 58.00                23.00               388.00
10                23.00                21.00               358.00
11                59.00                68.00               483.00
12                69.00                38.00               415.00
13                50.00                19.00               224.00
14                18.00                15.00                73.00
15                35.00                 7.00                30.00
16                30.00                17.00               257.00
17                  NaN                  NaN                  NaN
18                35.00                39.00               285.00
19                80.00               105.00               574.00
20                19.00                16.00               177.00
21                11.00                 2.00                83.00
22                54.00                39.00               459.00
23                44.00                12.00               208.00
24                26.00                14.00                91.00
25                34.00                 8.00               170.00
26                16.00                15.00               152.00
27                42.00                49.00               330.00
28                 2.00                 1.00                55.00
29                 3.00                 1.00                17.00
30                24.00                 6.00                33.00
31                20.00                 6.00                78.00
32                  NaN                  NaN                  NaN

     targeted_qb_rating              targets                yards  \
0                 95.00                90.00               628.00
1                 82.30                65.00               431.00
2                110.20               104.00               858.00
3                 98.70               104.00               911.00
4                 56.20                83.00               418.00
5                123.10                90.00               793.00
6                124.90               100.00               938.00
7                   NaN                  NaN                  NaN
8                115.20                74.00               709.00
9                 68.00                40.00               373.00
10                26.40                42.00               224.00
11                99.20                94.00               771.00
12                98.50                59.00               565.00
13                84.30                34.00               331.00
14                82.80                17.00                66.00
15                96.30                 9.00                64.00
16                56.90                31.00               168.00
17                  NaN                  NaN                  NaN
18               117.60                57.00               580.00
19               104.60               153.00             1,486.00
20               130.70                19.00               132.00
21                39.60                 7.00                19.00
22                84.50                66.00               385.00
23               149.30                18.00               246.00
24               126.20                17.00               163.00
25                60.00                18.00                90.00
26                94.30                25.00               116.00
27                70.10                76.00               561.00
28                56.30                 2.00                 2.00
29                16.70                 2.00                 3.00
30               111.10                 6.00                64.00
31               101.90                13.00                68.00
32                  NaN                  NaN                  NaN

      yards_after_catch  yards_after_catch_per_reception  yards_per_reception  \
0                370.00                             5.90                10.00
1                152.00                             4.00                11.30
2                396.00                             5.10                11.10
3                267.00                             3.80                13.00
4                161.00                             3.70                 9.70
5                348.00                             5.40                12.40
6                656.00                             8.30                11.90
7                   NaN                              NaN                  NaN
8                145.00                             3.10                15.10
9                 53.00                             2.30                16.20
10                67.00                             3.20                10.70
11               374.00                             5.50                11.30
12               143.00                             3.80                14.90
13                27.00                             1.40                17.40
14               114.00                             7.60                 4.40
15                34.00                             4.90                 9.10
16                65.00                             3.80                 9.90
17                  NaN                              NaN                  NaN
18               218.00                             5.60                14.90
19               627.00                             6.00                14.20
20                38.00                             2.40                 8.30
21                10.00                             5.00                 9.50
22               113.00                             2.90                 9.90
23                19.00                             1.60                20.50
24                71.00                             5.10                11.60
25                17.00                             2.10                11.30
26                34.00                             2.30                 7.70
27               343.00                             7.00                11.40
28                 1.00                             1.00                 2.00
29                 1.00                             1.00                 3.00
30                30.00                             5.00                10.70
31                11.00                             1.80                11.30
32                  NaN                              NaN                  NaN

                   yprr                  ypt
0                  1.32                 6.98
1                  0.88                 6.63
2                  1.64                 8.25
3                  1.50                 8.76
4                  0.78                 5.04
5                  2.05                 8.81
6                  2.39                 9.38
7                   NaN                  NaN
8                  2.22                 9.58
9                  0.96                 9.32
10                 0.63                 5.33
11                 1.60                 8.20
12                 1.36                 9.58
13                 1.48                 9.74
14                 0.90                 3.88
15                 2.13                 7.11
16                 0.65                 5.42
17                  NaN                  NaN
18                 2.04                10.18
19                 2.59                 9.71
20                 0.75                 6.95
21                 0.23                 2.71
22                 0.84                 5.83
23                 1.18                13.67
24                 1.79                 9.59
25                 0.53                 5.00
26                 0.76                 4.64
27                 1.70                 7.38
28                 0.04                 1.00
29                 0.18                 1.50
30                 1.94                10.67
31                 0.87                 5.23
32                  NaN                  NaN

In [34]:
df_wr23rz = df_wr23r.fillna(0) # replace nan values with 0
df_wr23r = df_wr23r.dropna() # remove nan

In [35]:
print(df_rookies) # show nan values

                    Rnd            Player                  Age  Rookie Year  \
0                  1.00      Drake London                21.00         2022
1                  1.00    Garrett Wilson                22.00         2022
2                  1.00       Chris Olave                22.00         2022
3                  1.00  Jameson Williams                21.00         2022
4                  1.00      Jahan Dotson                22.00         2022
..                  ...               ...                  ...          ...
25                 7.00  Devin Aromashodu                22.00         2006
26                 7.00       Ben Obomanu                22.00         2006
27                 7.00    David Anderson                23.00         2006
28                 7.00   Marques Colston                23.00         2006
29                 7.00     Kevin McMahan                  NaN         2006

    avg_depth_of_target      avoided_tackles       caught_percent  \
0                 11.20                 8.00                63.20
1                 11.00                22.00                59.70
2                 14.90                 2.00                63.20
3                 19.30                 0.00                12.50
4                 15.40                 2.00                62.50
..                  ...                  ...                  ...
25                  NaN                  NaN                  NaN
26                  NaN                  NaN                  NaN
27                 6.00                 3.00               100.00
28                10.90                 5.00                64.20
29                  NaN                  NaN                  NaN

         grades_offense              longest           receptions  \
0                 83.20                40.00                72.00
1                 82.70                60.00                83.00
2                 82.50                53.00                72.00
3                 63.40                41.00                 1.00
4                 70.50                61.00                35.00
..                  ...                  ...                  ...
25                  NaN                  NaN                  NaN
26                  NaN                  NaN                  NaN
27                78.40                27.00                 1.00
28                81.50                86.00                70.00
29                  NaN                  NaN                  NaN

                 routes   targeted_qb_rating              targets  \
0                419.00                87.10               114.00
1                595.00                91.50               139.00
2                431.00                86.30               114.00
3                 37.00                88.00                 8.00
4                376.00               102.90                56.00
..                  ...                  ...                  ...
25                  NaN                  NaN                  NaN
26                  NaN                  NaN                  NaN
27                 6.00               118.80                 1.00
28               447.00               108.30               109.00
29                  NaN                  NaN                  NaN

                  yards    yards_after_catch  yards_after_catch_per_reception  \
0                866.00               231.00                             3.20
1              1,103.00               389.00                             4.70
2              1,044.00               219.00                             3.00
3                 41.00                 5.00                             5.00
4                523.00               144.00                             4.10
..                  ...                  ...                              ...
25                  NaN                  NaN                              NaN
26                  NaN                  NaN                              NaN
27                27.00                21.00                            21.00
28             1,038.00               354.00                             5.10
29                  NaN                  NaN                              NaN

    yards_per_reception                 yprr                  ypt
0                 12.00                 2.07                 7.60
1                 13.30                 1.85                 7.94
2                 14.50                 2.42                 9.16
3                 41.00                 1.11                 5.12
4                 14.90                 1.39                 9.34
..                  ...                  ...                  ...
25                  NaN                  NaN                  NaN
26                  NaN                  NaN                  NaN
27                27.00                 4.50                27.00
28                14.80                 2.32                 9.52
29                  NaN                  NaN                  NaN

[1210 rows x 19 columns]

In [36]:
df_rookiesz = df_rookies.fillna(0) # replace nan values with 0
df_rookies = df_rookies.dropna() # remove nan

In [37]:
print(df_rookiesz)
print(df_rookies)

                    Rnd            Player                  Age  Rookie Year  \
0                  1.00      Drake London                21.00         2022
1                  1.00    Garrett Wilson                22.00         2022
2                  1.00       Chris Olave                22.00         2022
3                  1.00  Jameson Williams                21.00         2022
4                  1.00      Jahan Dotson                22.00         2022
..                  ...               ...                  ...          ...
25                 7.00  Devin Aromashodu                22.00         2006
26                 7.00       Ben Obomanu                22.00         2006
27                 7.00    David Anderson                23.00         2006
28                 7.00   Marques Colston                23.00         2006
29                 7.00     Kevin McMahan                 0.00         2006

    avg_depth_of_target      avoided_tackles       caught_percent  \
0                 11.20                 8.00                63.20
1                 11.00                22.00                59.70
2                 14.90                 2.00                63.20
3                 19.30                 0.00                12.50
4                 15.40                 2.00                62.50
..                  ...                  ...                  ...
25                 0.00                 0.00                 0.00
26                 0.00                 0.00                 0.00
27                 6.00                 3.00               100.00
28                10.90                 5.00                64.20
29                 0.00                 0.00                 0.00

         grades_offense              longest           receptions  \
0                 83.20                40.00                72.00
1                 82.70                60.00                83.00
2                 82.50                53.00                72.00
3                 63.40                41.00                 1.00
4                 70.50                61.00                35.00
..                  ...                  ...                  ...
25                 0.00                 0.00                 0.00
26                 0.00                 0.00                 0.00
27                78.40                27.00                 1.00
28                81.50                86.00                70.00
29                 0.00                 0.00                 0.00

                 routes   targeted_qb_rating              targets  \
0                419.00                87.10               114.00
1                595.00                91.50               139.00
2                431.00                86.30               114.00
3                 37.00                88.00                 8.00
4                376.00               102.90                56.00
..                  ...                  ...                  ...
25                 0.00                 0.00                 0.00
26                 0.00                 0.00                 0.00
27                 6.00               118.80                 1.00
28               447.00               108.30               109.00
29                 0.00                 0.00                 0.00

                  yards    yards_after_catch  yards_after_catch_per_reception  \
0                866.00               231.00                             3.20
1              1,103.00               389.00                             4.70
2              1,044.00               219.00                             3.00
3                 41.00                 5.00                             5.00
4                523.00               144.00                             4.10
..                  ...                  ...                              ...
25                 0.00                 0.00                             0.00
26                 0.00                 0.00                             0.00
27                27.00                21.00                            21.00
28             1,038.00               354.00                             5.10
29                 0.00                 0.00                             0.00

    yards_per_reception                 yprr                  ypt
0                 12.00                 2.07                 7.60
1                 13.30                 1.85                 7.94
2                 14.50                 2.42                 9.16
3                 41.00                 1.11                 5.12
4                 14.90                 1.39                 9.34
..                  ...                  ...                  ...
25                 0.00                 0.00                 0.00
26                 0.00                 0.00                 0.00
27                27.00                 4.50                27.00
28                14.80                 2.32                 9.52
29                 0.00                 0.00                 0.00

[1210 rows x 19 columns]
                    Rnd            Player                  Age  Rookie Year  \
0                  1.00      Drake London                21.00         2022
1                  1.00    Garrett Wilson                22.00         2022
2                  1.00       Chris Olave                22.00         2022
3                  1.00  Jameson Williams                21.00         2022
4                  1.00      Jahan Dotson                22.00         2022
..                  ...               ...                  ...          ...
13                 4.00  Brandon Marshall                22.00         2006
19                 6.00    Delanie Walker                22.00         2006
21                 6.00         Jeff Webb                24.00         2006
27                 7.00    David Anderson                23.00         2006
28                 7.00   Marques Colston                23.00         2006

    avg_depth_of_target      avoided_tackles       caught_percent  \
0                 11.20                 8.00                63.20
1                 11.00                22.00                59.70
2                 14.90                 2.00                63.20
3                 19.30                 0.00                12.50
4                 15.40                 2.00                62.50
..                  ...                  ...                  ...
13                14.60                 8.00                57.10
19                 3.00                 1.00                50.00
21                 8.00                 0.00                75.00
27                 6.00                 3.00               100.00
28                10.90                 5.00                64.20

         grades_offense              longest           receptions  \
0                 83.20                40.00                72.00
1                 82.70                60.00                83.00
2                 82.50                53.00                72.00
3                 63.40                41.00                 1.00
4                 70.50                61.00                35.00
..                  ...                  ...                  ...
13                74.00                71.00                20.00
19                62.60                29.00                 2.00
21                61.40                11.00                 3.00
27                78.40                27.00                 1.00
28                81.50                86.00                70.00

                 routes   targeted_qb_rating              targets  \
0                419.00                87.10               114.00
1                595.00                91.50               139.00
2                431.00                86.30               114.00
3                 37.00                88.00                 8.00
4                376.00               102.90                56.00
..                  ...                  ...                  ...
13               155.00                93.60                35.00
19                19.00                75.00                 4.00
21                19.00                88.50                 4.00
27                 6.00               118.80                 1.00
28               447.00               108.30               109.00

                  yards    yards_after_catch  yards_after_catch_per_reception  \
0                866.00               231.00                             3.20
1              1,103.00               389.00                             4.70
2              1,044.00               219.00                             3.00
3                 41.00                 5.00                             5.00
4                523.00               144.00                             4.10
..                  ...                  ...                              ...
13               309.00               103.00                             5.20
19                30.00                31.00                            15.50
21                23.00                 1.00                             0.30
27                27.00                21.00                            21.00
28             1,038.00               354.00                             5.10

    yards_per_reception                 yprr                  ypt
0                 12.00                 2.07                 7.60
1                 13.30                 1.85                 7.94
2                 14.50                 2.42                 9.16
3                 41.00                 1.11                 5.12
4                 14.90                 1.39                 9.34
..                  ...                  ...                  ...
13                15.50                 1.99                 8.83
19                15.00                 1.58                 7.50
21                 7.70                 1.21                 5.75
27                27.00                 4.50                27.00
28                14.80                 2.32                 9.52

[342 rows x 19 columns]

In [38]:
df_1k = pd.read_csv('1kseasons.csv')
df_1k.tail()

               Player  Rookie year  1,000 Yard Seasons
572  Devin Aromashodu         2006                   0
573       Ben Obomanu         2006                   0
574    David Anderson         2006                   0
575   Marques Colston         2006                   7
576     Kevin McMahan         2006                   0

In [39]:
dfrookies = pd.merge(df_rookies, df_1k, on= 'Player', how= 'left')
dfrookies.shape

(346, 21)

In [40]:
dfrookiesz = pd.merge(df_rookies, df_1k, on= 'Player', how= 'left')
dfrookies.shape

(346, 21)

In [41]:
print(dfrookies)
print(dfrookiesz)

                     Rnd            Player                  Age  Rookie Year  \
0                   1.00      Drake London                21.00         2022
1                   1.00    Garrett Wilson                22.00         2022
2                   1.00       Chris Olave                22.00         2022
3                   1.00  Jameson Williams                21.00         2022
4                   1.00      Jahan Dotson                22.00         2022
..                   ...               ...                  ...          ...
341                 4.00  Brandon Marshall                22.00         2006
342                 6.00    Delanie Walker                22.00         2006
343                 6.00         Jeff Webb                24.00         2006
344                 7.00    David Anderson                23.00         2006
345                 7.00   Marques Colston                23.00         2006

     avg_depth_of_target      avoided_tackles       caught_percent  \
0                  11.20                 8.00                63.20
1                  11.00                22.00                59.70
2                  14.90                 2.00                63.20
3                  19.30                 0.00                12.50
4                  15.40                 2.00                62.50
..                   ...                  ...                  ...
341                14.60                 8.00                57.10
342                 3.00                 1.00                50.00
343                 8.00                 0.00                75.00
344                 6.00                 3.00               100.00
345                10.90                 5.00                64.20

          grades_offense              longest           receptions  ...  \
0                  83.20                40.00                72.00  ...
1                  82.70                60.00                83.00  ...
2                  82.50                53.00                72.00  ...
3                  63.40                41.00                 1.00  ...
4                  70.50                61.00                35.00  ...
..                   ...                  ...                  ...  ...
341                74.00                71.00                20.00  ...
342                62.60                29.00                 2.00  ...
343                61.40                11.00                 3.00  ...
344                78.40                27.00                 1.00  ...
345                81.50                86.00                70.00  ...

      targeted_qb_rating              targets                yards  \
0                  87.10               114.00               866.00
1                  91.50               139.00             1,103.00
2                  86.30               114.00             1,044.00
3                  88.00                 8.00                41.00
4                 102.90                56.00               523.00
..                   ...                  ...                  ...
341                93.60                35.00               309.00
342                75.00                 4.00                30.00
343                88.50                 4.00                23.00
344               118.80                 1.00                27.00
345               108.30               109.00             1,038.00

       yards_after_catch  yards_after_catch_per_reception  \
0                 231.00                             3.20
1                 389.00                             4.70
2                 219.00                             3.00
3                   5.00                             5.00
4                 144.00                             4.10
..                   ...                              ...
341               103.00                             5.20
342                31.00                            15.50
343                 1.00                             0.30
344                21.00                            21.00
345               354.00                             5.10

     yards_per_reception                 yprr                  ypt  \
0                  12.00                 2.07                 7.60
1                  13.30                 1.85                 7.94
2                  14.50                 2.42                 9.16
3                  41.00                 1.11                 5.12
4                  14.90                 1.39                 9.34
..                   ...                  ...                  ...
341                15.50                 1.99                 8.83
342                15.00                 1.58                 7.50
343                 7.70                 1.21                 5.75
344                27.00                 4.50                27.00
345                14.80                 2.32                 9.52

     Rookie year  1,000 Yard Seasons
0           2022                   0
1           2022                   2
2           2022                   2
3           2022                   0
4           2022                   0
..           ...                 ...
341         2006                   8
342         2006                   1
343         2006                   0
344         2006                   0
345         2006                   7

[346 rows x 21 columns]
                     Rnd            Player                  Age  Rookie Year  \
0                   1.00      Drake London                21.00         2022
1                   1.00    Garrett Wilson                22.00         2022
2                   1.00       Chris Olave                22.00         2022
3                   1.00  Jameson Williams                21.00         2022
4                   1.00      Jahan Dotson                22.00         2022
..                   ...               ...                  ...          ...
341                 4.00  Brandon Marshall                22.00         2006
342                 6.00    Delanie Walker                22.00         2006
343                 6.00         Jeff Webb                24.00         2006
344                 7.00    David Anderson                23.00         2006
345                 7.00   Marques Colston                23.00         2006

     avg_depth_of_target      avoided_tackles       caught_percent  \
0                  11.20                 8.00                63.20
1                  11.00                22.00                59.70
2                  14.90                 2.00                63.20
3                  19.30                 0.00                12.50
4                  15.40                 2.00                62.50
..                   ...                  ...                  ...
341                14.60                 8.00                57.10
342                 3.00                 1.00                50.00
343                 8.00                 0.00                75.00
344                 6.00                 3.00               100.00
345                10.90                 5.00                64.20

          grades_offense              longest           receptions  ...  \
0                  83.20                40.00                72.00  ...
1                  82.70                60.00                83.00  ...
2                  82.50                53.00                72.00  ...
3                  63.40                41.00                 1.00  ...
4                  70.50                61.00                35.00  ...
..                   ...                  ...                  ...  ...
341                74.00                71.00                20.00  ...
342                62.60                29.00                 2.00  ...
343                61.40                11.00                 3.00  ...
344                78.40                27.00                 1.00  ...
345                81.50                86.00                70.00  ...

      targeted_qb_rating              targets                yards  \
0                  87.10               114.00               866.00
1                  91.50               139.00             1,103.00
2                  86.30               114.00             1,044.00
3                  88.00                 8.00                41.00
4                 102.90                56.00               523.00
..                   ...                  ...                  ...
341                93.60                35.00               309.00
342                75.00                 4.00                30.00
343                88.50                 4.00                23.00
344               118.80                 1.00                27.00
345               108.30               109.00             1,038.00

       yards_after_catch  yards_after_catch_per_reception  \
0                 231.00                             3.20
1                 389.00                             4.70
2                 219.00                             3.00
3                   5.00                             5.00
4                 144.00                             4.10
..                   ...                              ...
341               103.00                             5.20
342                31.00                            15.50
343                 1.00                             0.30
344                21.00                            21.00
345               354.00                             5.10

     yards_per_reception                 yprr                  ypt  \
0                  12.00                 2.07                 7.60
1                  13.30                 1.85                 7.94
2                  14.50                 2.42                 9.16
3                  41.00                 1.11                 5.12
4                  14.90                 1.39                 9.34
..                   ...                  ...                  ...
341                15.50                 1.99                 8.83
342                15.00                 1.58                 7.50
343                 7.70                 1.21                 5.75
344                27.00                 4.50                27.00
345                14.80                 2.32                 9.52

     Rookie year  1,000 Yard Seasons
0           2022                   0
1           2022                   2
2           2022                   2
3           2022                   0
4           2022                   0
..           ...                 ...
341         2006                   8
342         2006                   1
343         2006                   0
344         2006                   0
345         2006                   7

[346 rows x 21 columns]

In [42]:
dfrookies.head()

,Rnd,Player,Age,Rookie Year,avg_depth_of_target,avoided_tackles,caught_percent,grades_offense,longest,receptions,...,targeted_qb_rating,targets,yards,yards_after_catch,yards_after_catch_per_reception,yards_per_reception,yprr,ypt,Rookie year,"1,000 Yard Seasons"
0,1.00,Drake London,21.00,2022,11.20,8.00,63.20,83.20,40.00,72.00,...,87.10,114.00,866.00,231.00,3.20,12.00,2.07,7.60,2022,0
1,1.00,Garrett Wilson,22.00,2022,11.00,22.00,59.70,82.70,60.00,83.00,...,91.50,139.00,"1,103.00",389.00,4.70,13.30,1.85,7.94,2022,2
2,1.00,Chris Olave,22.00,2022,14.90,2.00,63.20,82.50,53.00,72.00,...,86.30,114.00,"1,044.00",219.00,3.00,14.50,2.42,9.16,2022,2
3,1.00,Jameson Williams,21.00,2022,19.30,0.00,12.50,63.40,41.00,1.00,...,88.00,8.00,41.00,5.00,5.00,41.00,1.11,5.12,2022,0
4,1.00,Jahan Dotson,22.00,2022,15.40,2.00,62.50,70.50,61.00,35.00,...,102.90,56.00,523.00,144.00,4.10,14.90,1.39,9.34,2022,0

In [43]:
dfrookiesz.head()

,Rnd,Player,Age,Rookie Year,avg_depth_of_target,avoided_tackles,caught_percent,grades_offense,longest,receptions,...,targeted_qb_rating,targets,yards,yards_after_catch,yards_after_catch_per_reception,yards_per_reception,yprr,ypt,Rookie year,"1,000 Yard Seasons"
0,1.00,Drake London,21.00,2022,11.20,8.00,63.20,83.20,40.00,72.00,...,87.10,114.00,866.00,231.00,3.20,12.00,2.07,7.60,2022,0
1,1.00,Garrett Wilson,22.00,2022,11.00,22.00,59.70,82.70,60.00,83.00,...,91.50,139.00,"1,103.00",389.00,4.70,13.30,1.85,7.94,2022,2
2,1.00,Chris Olave,22.00,2022,14.90,2.00,63.20,82.50,53.00,72.00,...,86.30,114.00,"1,044.00",219.00,3.00,14.50,2.42,9.16,2022,2
3,1.00,Jameson Williams,21.00,2022,19.30,0.00,12.50,63.40,41.00,1.00,...,88.00,8.00,41.00,5.00,5.00,41.00,1.11,5.12,2022,0
4,1.00,Jahan Dotson,22.00,2022,15.40,2.00,62.50,70.50,61.00,35.00,...,102.90,56.00,523.00,144.00,4.10,14.90,1.39,9.34,2022,0

In [44]:
dfrookies.to_csv('df_rookies.csv')
dfrookiesz.to_csv('df_rookiesz.csv')
df_wr23r.to_csv('df_rookiedata_2023.csv')
df_wr23rz.to_csv('df_rookiedata_2023z.csv')